apiVersion: v1
kind: ConfigMap
metadata:
  name: load-data-config
  labels:
    app: sdc
data:
  load_db.sql: |-
    -- Load data
    \COPY public.products FROM '/work-dir/products.csv' DELIMITER ',' CSV HEADER;
    \COPY public.styles FROM '/work-dir/styles.csv' DELIMITER ',' CSV NULL AS 'null' HEADER;
    \COPY public.features FROM '/work-dir/features.csv' DELIMITER ',' CSV HEADER;
    \COPY public.related FROM '/work-dir/related.csv' DELIMITER ',' CSV HEADER;
    \COPY public.skus FROM '/work-dir/skus.csv' DELIMITER ',' CSV HEADER;
    \COPY public.photos FROM '/work-dir/photos.csv' DELIMITER ',' CSV HEADER;
  download.sh: |-
    #!/bin/bash
    apk update
    apk add wget
    wget --version

    IDS=('1-W_7beRPqrP95t6DTpxdSCNsvn6gM8GM' '1zHrArvW4JI_K5Kj9uUyT9jFK4OLkrbNc' '11vpwszUgdEuT26QIJaswTF6z2d-m-uZK' '1RrUnymxIrJlbBDPfjVerYxixwpdQttwI' '1a8FjukI7bR4zav3MIcIETHGkEC5Oazhz' '1u-AQPr3pauwCophsmjcg-qGy7zabfXcR')
    NAMES=('products.csv' 'styles.csv' 'features.csv' 'related.csv' 'skus.csv' 'photos.csv')
    for i in "${!IDS[@]}"; do
      wget --load-cookies cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id='"${IDS[i]}" -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=${IDS[i]}" -O /work-dir/${NAMES[i]} && rm -rf cookies.txt
    done
  load.sh: |-
    export PGPASSWORD=dumb1234
    psql -U pd -d sdc -p 5432 -h db -f /data/load_db.sql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-data
spec:
  template:
    spec:
      initContainers:
        - name: download-csv
          image: bash:alpine3.16
          command: ["bash", "/data/download.sh"]
          volumeMounts:
            - name: workdir
              mountPath: "/work-dir"
            - name: load-data-config
              mountPath: "/data"
      containers:
        - name: postgres-load
          image: postgres:14.6-alpine3.17
          command: ["bash", "/data/load.sh"]
          volumeMounts:
            - name: workdir
              mountPath: "/work-dir"
            - name: load-data-config
              mountPath: "/data"
      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
        - name: load-data-config
          configMap:
            name: load-data-config
